HTTP/1.1 202 Accepted
Connection: keep-alive
Transfer-Encoding: chunked
Status: 202 Accepted
Cache-Control: no-cache
Strict-Transport-Security: max-age=631138519
X-Permitted-Cross-Domain-Policies: none
X-Xss-Protection: 1; mode=block
X-Request-Id: 8cd229d2-6418-4a62-a71f-f22c0a5fa06b
Location: /api/jobs/605cb60f148eb31740c39174
X-Download-Options: noopen
X-Runtime: 0.283859
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff


{}
