HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json
Transfer-Encoding: chunked
Vary: Accept-Encoding
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=631138519
X-Permitted-Cross-Domain-Policies: none
X-Xss-Protection: 1; mode=block
X-Request-Id: 6d43896a-50db-4cca-b76f-25894cd482dd
X-Download-Options: noopen
Etag: W/"cefb5c84d102620e986f7cd8b89cf145"
X-Runtime: 0.030745
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src https: 'self'; child-src *.recurly.com share.intercom.io www.youtube.com player.vimeo.com fast.wistia.net; connect-src https: 'self' api.intercom.io api-iam.intercom.io api-ping.intercom.io nexus-websocket-a.intercom.io nexus-websocket-b.intercom.io nexus-long-poller-a.intercom.io nexus-long-poller-b.intercom.io wss://nexus-websocket-a.intercom.io wss://nexus-websocket-b.intercom.io uploads.intercomcdn.com uploads.intercomusercontent.com; font-src https: 'self' js.intercomcdn.com; frame-ancestors 'none'; img-src https: 'self' data: js.intercomcdn.com static.intercomassets.com uploads.intercomcdn.com uploads.intercomusercontent.com; media-src https: js.intercomcdn.com; script-src 'unsafe-inline' 'unsafe-eval' https: app.intercom.io widget.intercom.io js.intercomcdn.com; style-src 'unsafe-inline' https:
Date: Fri, 31 Mar 2017 23:17:01 GMT
X-Powered-By: Phusion Passenger 5.1.2
Server: nginx + Phusion Passenger 5.1.2
Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Headers: X-Api-Version, Authorization, Content-Type
Access-Control-Max-Age: 3628800
Via: 1.1 vegur

{"href":"/api/ideas/110689","id":110689,"name":"ImplementationIdeaTest","description":"Implement and test the feature.","strategic_value":"polarity","notes":"autotoxication","percent_done":78,"effort":2,"tags":["electrotypy","monoservice"],"fields":{"pp_lanes":"Lane 2","pp_legend":"Goal 1"},"timestamps":{"created_at":"2017-03-31T14:36:40-07:00","updated_at":"2017-03-31T15:17:52-07:00"},"links":{"roadmap":{"href":"/api/roadmaps/5912"},"external_links":{"href":"/api/ideas/110689/external_links"}}}
