HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/vnd.productplan.bar; type=collection
Transfer-Encoding: chunked
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=631138519
X-Permitted-Cross-Domain-Policies: none
X-Xss-Protection: 1; mode=block
X-Request-Id: 56c14ef2-a25c-416f-a905-ce7c451d674c
Link: </api/roadmaps/7302/bars?pagination=by%3Did%2Cfrom%3D262149%2Citems%3D500>; rel="next", </api/roadmaps/7302/bars?pagination=by%3Did%2Citems%3D500>; rel="first"
X-Download-Options: noopen
Etag: W/"460c63a843c1c075a1dad5624d790fa6"
X-Runtime: 0.324888
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src https: 'self'; child-src *.recurly.com share.intercom.io www.youtube.com player.vimeo.com fast.wistia.net; connect-src https: 'self' api.intercom.io api-iam.intercom.io api-ping.intercom.io nexus-websocket-a.intercom.io nexus-websocket-b.intercom.io nexus-long-poller-a.intercom.io nexus-long-poller-b.intercom.io wss://nexus-websocket-a.intercom.io wss://nexus-websocket-b.intercom.io uploads.intercomcdn.com uploads.intercomusercontent.com sockjs.pusher.com wss://ws.pusherapp.com; font-src https: 'self' js.intercomcdn.com; frame-ancestors 'none'; img-src https: 'self' data: js.intercomcdn.com static.intercomassets.com uploads.intercomcdn.com uploads.intercomusercontent.com; media-src https: js.intercomcdn.com; script-src 'unsafe-inline' 'unsafe-eval' https: app.intercom.io widget.intercom.io js.intercomcdn.com; style-src 'unsafe-inline' https:
Date: Thu, 06 Sep 2018 22:12:15 GMT
X-Powered-By: Phusion Passenger 5.3.2
Server: nginx + Phusion Passenger 5.3.2
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Headers: X-Api-Version, Authorization, Content-Type
Access-Control-Max-Age: 3628800
Via: 1.1 vegur

[{"href":"/api/bars/110240","id":110240,"name":"API Bar","start_date":"2017-06-21","end_date":"2017-09-21","description":"desc","strategic_value":"low","notes":"notes","percent_done":0,"effort":5,"tags":["ssl", "docker"],"fields":{"pp_lanes":"Lane 2","pp_legend":"Goal 4"},"timestamps":{"created_at":"2017-10-03T12:58:07-07:00","updated_at":"2017-10-05T12:02:07-07:00"},"links":{"roadmap":{"href":"/api/roadmaps/7302"},"child_bars":{"href":"/api/bars/1102402/child_bars"},"external_links":{"href":"/api/bars/1102402/external_links"}}}]
